programs:
    simple_sleep:
        command: "/bin/sleep 10"
        numprocs: 1
        umask: 022
        directory: /tmp
        autostart: false
        autorestart: never
        exitcodes: 0
        startretries: 2
        startsecs: 1
        stopsignal: TERM
        stopwaitsecs: 3
        stdout: /tmp/simple_sleep.stdout
        stderr: /tmp/simple_sleep.stderr
    
    long_sleep:
        command: "/bin/sleep 30"
        numprocs: 2
        umask: 022
        directory: /tmp
        autostart: true
        autorestart: always
        exitcodes: 0
        startretries: 2
        startsecs: 2
        stopsignal: TERM
        stopwaitsecs: 5
        stdout: /tmp/long_sleep.stdout
        stderr: /tmp/long_sleep.stderr
        env:
            TEST_ENV: "working"
